PregnancyStore = [];

//Pregancy types. Both butt and normal. Each type represents the father of this baby.
const PREGNANCY_IMP                   =   1;
const PREGNANCY_MINOTAUR              =   2;
const PREGNANCY_MOUSE                 =   4;
const PREGNANCY_OVIELIXIR_EGGS        =   5; //Also caused by Phoenixes apparently
const PREGNANCY_HELL_HOUND            =   6;
const PREGNANCY_CENTAUR               =   7;
const PREGNANCY_MARBLE                =   8;
const PREGNANCY_BUNNY                 =   9;
const PREGNANCY_ANEMONE               =  10;
const PREGNANCY_AMILY                 =  11;
const PREGNANCY_IZMA                  =  12;
const PREGNANCY_SPIDER                =  13;
const PREGNANCY_BASILISK              =  14;
const PREGNANCY_DRIDER_EGGS           =  15;
const PREGNANCY_GOO_GIRL              =  16;
const PREGNANCY_EMBER                 =  17;
const PREGNANCY_BENOIT                =  18;
const PREGNANCY_SATYR                 =  19;
const PREGNANCY_COTTON                =  20;
const PREGNANCY_URTA                  =  21;
const PREGNANCY_SAND_WITCH            =  22;
const PREGNANCY_FROG_GIRL             =  23;
const PREGNANCY_FAERIE                =  24; //Indicates you are carrying either a phouka or faerie baby. Which one is determined by the PREGNANCY_CORRUPTION flag
const PREGNANCY_PLAYER                =  25; //The player is the father. Will be used when an NPC is able to have children from multiple different fathers.
const PREGNANCY_BEE_EGGS              =  26;
const PREGNANCY_SANDTRAP_FERTILE      =  27;
const PREGNANCY_SANDTRAP              =  28;
const PREGNANCY_JOJO                  =  29; //So we can track them separately from other mouse pregnancies
const PREGNANCY_KELT                  =  30; //So we can track them separately from other centaur pregnancies
const PREGNANCY_TAOTH                 =  31;
const PREGNANCY_GOO_STUFFED           =  32; //Used to fill the player's ass and/or vagina when Valeria has a goo girl take up residence. This prevents any other form of pregnancy from taking hold. Does not respond to ovielixirs.
const PREGNANCY_WORM_STUFFED          =  33; //Used to fill the player's vagina when the worms take up residence. This prevents any other form of pregnancy from taking hold. Does not respond to ovielixirs.
const PREGNANCY_MINERVA               =  34;
const PREGNANCY_BEHEMOTH              =  35;
const PREGNANCY_PHOENIX               =  36;
const PREGNANCY_ANDY                  =  37; //This is functionally the same as Satyr but less corrupt. 10% chance of fauns, if ever implemented.

const PREG_NOT_PREGANT                =   0; //The PREG_* consts are returned by the size function
const PREG_NO_SIGNS_UNKNOWN           =   1; //NPC has conceived but doesn’t know she’s pregnant, no visible signs
const PREG_NO_SIGNS_KNOWN             =   2; //NPC is in the first trimester, knows she’s pregnant
const PREG_START_BULGE                =   3; //NPC is in the first trimester, belly is just starting to bulge
const PREG_SWOLLEN                    =   4; //NPC is in the second trimester, belly is small but definitely swollen
const PREG_SIZEABLE                   =   5; //NPC is in the second trimester, belly is now sizable
const PREG_BLATANT                    =   6; //NPC is in the third trimester, belly is blatantly bulging
const PREG_FULL_TERM                  =   7; //NPC is in the third trimester, belly is big as it will get for a normal pregnancy
const PREG_OVERDUE                    =   8; //NPC is overdue. Usually means a centaur baby, twins or some similar condition. Effectively looks 10 months pregnant
const PREG_VERY_OVERDUE               =   9; //NPC is very overdue. Probably triplets or more. Effectively looks 11 months pregnant
//Old Value, replaced in Saves.unFuckSave()        const PREGNANCY_BUTT_BEE              =   2;
//Old Value, replaced in Saves.unFuckSave()        const PREGNANCY_BUTT_DRIDER           =   3;
//Old Value, replaced in Saves.unFuckSave()        const PREGNANCY_BUTT_SANDTRAP_FERTILE =   4;
//Old Value, replaced in Saves.unFuckSave()        const PREGNANCY_BUTT_SANDTRAP         =   5; //Sandtrap did not have fertilized eggs

const INCUBATION_IMP                  = 432; //Time for standard imps. Imp lords, Ceraph, Lilium and the imp horde cause slightly faster pregnancies
const INCUBATION_MINOTAUR             = 432;
const INCUBATION_MOUSE                = 350;
const INCUBATION_OVIELIXIR_EGGS       =  50;
const INCUBATION_HELL_HOUND           = 352;
const INCUBATION_CENTAUR              = 420;
const INCUBATION_MARBLE               = 368;
const INCUBATION_BUNNY_BABY           = 200;
const INCUBATION_BUNNY_EGGS           = 808; //High time indicates neon egg pregnancy
const INCUBATION_ANEMONE              = 256;
const INCUBATION_IZMA                 = 300;
const INCUBATION_SPIDER               = 400;
const INCUBATION_BASILISK             = 250;
const INCUBATION_DRIDER               = 400;
const INCUBATION_GOO_GIRL             =  85;
const INCUBATION_EMBER                = 336;
const INCUBATION_SATYR                = 160;
const INCUBATION_COTTON               = 350;
const INCUBATION_URTA                 = 515;
const INCUBATION_SAND_WITCH           = 360;
const INCUBATION_FROG_GIRL            =  30;
const INCUBATION_FAERIE               = 200;
const INCUBATION_BEE                  =  48;
const INCUBATION_SANDTRAP             =  42;
const INCUBATION_HARPY                = 168;
const INCUBATION_SHIELA               =  72;
const INCUBATION_SALAMANDER           = 336;
const INCUBATION_MINERVA              = 216;
const INCUBATION_BEHEMOTH             =1440; //Sorry Behemoth, but Isabella wins.
const INCUBATION_PHOENIX              = 168;
const INCUBATION_KIHA                 = 384;
const INCUBATION_ISABELLA             =2160; //Longest pregnancy ever. 